
# POST http://localhost:3000/campaigns
# content-type: application/json

# {
#     "title": "Campanha 1"
# }


##

# GET http://localhost:3000/campaigns

https://api.fimca.com.br:8051/api/framework/v1/consultaSQLServer/RealizaConsulta/API.CAMPANHA/0/g
Authorization: Basic ZmVybmFuZG86VmVsb2NpZGFkZS4x